- name: Main
  hosts: all
  vars:
    swap_size_mb: 1024
    git_user_email: "contact@waterloorocketry.com"
    git_user_name: "Waterloo Rocketry"

  tasks:
    - name: Initial setup
      ansible.builtin.include_tasks:
        file: tasks/initial_setup.yml

    - name: GIT
      ansible.builtin.include_tasks:
        file: tasks/git.yml

    - name: NetworkManager
      ansible.builtin.include_tasks:
        file: tasks/networkmanager.yml

    - name: Docker
      ansible.builtin.include_tasks:
        file: tasks/docker.yml

    - name: Omnibus
      ansible.builtin.include_tasks:
        file: tasks/omnibus.yml
