services:
  omnibus-server:
    image: ghcr.io/waterloo-rocketry/omnibus-server@sha256:d5324bd442d4a9c5923e93e96df2daef899bf3c60c04efdb18183f53e2e1a2f5
    network_mode: host
    restart: unless-stopped

  omnibus-globallog:
    image: ghcr.io/waterloo-rocketry/omnibus-globallog@sha256:d8b5672d7aa9f117df5fed5fd051bf2a256c7a37860f8de7e029c950485022d0
    network_mode: host
    restart: unless-stopped
    depends_on:
      - omnibus-server
    volumes:
      - ./data:/data
    command: ["--outfolder", "/data"]

  omnibus-source-ljm:
    image: ghcr.io/waterloo-rocketry/omnibus-source-ljm@sha256:01bd741287e32b435df1c355c0b5c458cf469a926edd5e90bfcbc5884a1ffcad
    network_mode: host
    restart: unless-stopped
    depends_on:
      - omnibus-server
    volumes:
      - ./config:/config
  
  omnibus-ws-bridge:
    image: ghcr.io/waterloo-rocketry/omnibus-ws-bridge@sha256:248280b41c8e21030f2820deb56ede688a7bf9fcf30118493deefbba896e859d
    network_mode: host
    restart: unless-stopped
    depends_on:
      - omnibus-server
      - omnibus-ws-server

  omnibus-ws-server:
    image: ghcr.io/waterloo-rocketry/omnibus-ws-server@sha256:883c3480c25cc21a512ec13bee7e61f60dbd83be2b35a1839f3af15e6dd6c480
    network_mode: host
    restart: unless-stopped
    depends_on:
      - omnibus-server

  daqms:
    image: ghcr.io/waterloo-rocketry/omnibus-daqms@sha256:99626f8c4308a9367ca41a76a4c9cb9fc9f501321357d2d4fbb3035f130df27c
    restart: unless-stopped
    depends_on:
      - omnibus-server
    ports:
      - 8080:8080
